### ISSUE TITLE
Remove SurrealDB dependency [was: remove rocksdb dependency]

### ISSUE THREAD

**Issue by link2xt** [webxdc/appstore-bot#2]
It is a C++ dependency which always makes compilation troubles and is an overkill for appstore-bot usecase.

Maybe use SQLite in some form (rusqlite/sqlx) or simple files instead? Or at least https://docs.rs/sled/latest/sled/ which is already used in https://github.com/farooqkz/deltachat-discourse-loginbot/ if we absolutely need a key-value store.

I currently have the build fail while compiling `rocksdb/table/block_based/data_block_hash_index.cc`.

**Comment by Septias** [comment]
Can you try this? https://docs.rs/surrealdb/1.0.0-beta.9+20230402/surrealdb/engine/local/index.html

**Comment by Septias** [comment]
I can't really help much, I didn't have that problem... :/

**Comment by Septias** [comment]
yeah thats true, just saw your comment in dc
