### ISSUE TITLE
Application list is not displayed after clicking "update"

### ISSUE THREAD

**Issue by link2xt** [webxdc/appstore-bot#34]
On the current version https://github.com/webxdc/appstore-bot/commit/43167fc8d6f160aa295f921a67d9b72cc12812ed I have rebuilt the bot frontend and the bot from scratch, ran `import` with example applications, then started the bot. Sent the message "hello!" to the bot from my account, received an appstore.xdc. The .xdc opened on my phone and desktop. On the phone the appstore.xdc loads but the list is empty. On desktop the app contains the initial list, but after clicking "update" the list becomes empty and nothing is displayed anymore.

**Comment by Septias** [comment]
fixed in 9b11263bcac3d3cd84a00d0a7defc1027f8159c6
