### ISSUE TITLE
`appstore.xdc` received twice

### ISSUE THREAD

**Issue by r10s** [webxdc/appstore-bot#43]
i just sent "hi" to the appstore bot mail address - and received the `appstore.xdc` twice, with a difference of 12 seconds (i received one at 18:04:08 and the other at 18:04:20, both have different rfc-messsage-id.

i then requested an app from the bot; that words and was received only once.

i also tested the bot before (may 25), that time, i received the `appstore.xdc` only once.

**Comment by Septias** [comment]
Did you add the bot with the 1:1 invite qr. The bot will respond to a successfull setup with the appstore. If you write hi afterwards it's only logical, that you receive it twice.

**Comment by r10s** [comment]
i was already in a chat with the bot and sent one time "hi" to get a fresh .xdc

**Comment by r10s** [comment]
i double checked, yes it was only one "hi" - however, i am also failing to reproduce the issue, so might also be a temporary hickup, closing this for now
