### ISSUE TITLE
icon should not have transparency or alpha or so

### ISSUE THREAD

**Issue by r10s** [webxdc/appstore-bot#47]
for unique layouts and to not add burden to implementations,  we do not guarantee that transparency or alpha works at all.

we're also [saying that in the docs](https://docs.webxdc.org/spec.html#icon-files) - and we should not be a bad example with apps we create on our own :)

in this concrete case, things also look bad in dark mode, however, fix is to _remove_ transparency/alpha, not to make transparency look good in dark mode.

**Comment by adbenitez** [comment]
agree, but I think that is only a placeholder icon? at least I was not expecting that to be the final icon of the app store :thinking:
