### ISSUE TITLE
search inside the store is not working as expected

### ISSUE THREAD

**Issue by adbenitez** [webxdc/appstore-bot#51]
![image_2023-06-14_16-41-38](https://github.com/webxdc/appstore-bot/assets/24558636/3c716d78-538d-4bd0-854e-265b576da138)

**Comment by Septias** [comment]
You can try to play around with the [fuse-options](https://github.com/webxdc/appstore-bot/blob/3b52e362bfc7f5fa780005bfdf0033c02c64b3b6/frontend/src/entry-points/shop.tsx#LL21C1-L26C2) and try to find some better defaults for your liking. Possible values are defined here: https://fusejs.io/api/options.html

**Comment by adbenitez** [comment]
**NOTE:** author, app name and description should be considered in the search
