### ISSUE TITLE
Frontend does not open on Android with WebView 74

### ISSUE THREAD

**Issue by link2xt** [webxdc/appstore-bot#7]
When I open the .xdc that the bot sends me, it opens on Desktop, but on Android I only see the blank page. All other webxdc apps I have tried before work for me.

I have Android System WebView 74.0.3729.186. Vite.js documentation says it requires Chrome >=87 by default: https://vitejs.dev/guide/build.html#browser-compatibility and otherwise has to be configured to support older browsers.

Chrome 74 was released in 2019 which is not even that far away: https://developer.chrome.com/blog/new-in-chrome-74/
I would say appstore should support even older versions than this.

**Comment by Septias** [comment]
Since you have a good testing device, can you try this at some point?
