### ISSUE TITLE
Add `clippy::unwrap_used` lint

### ISSUE THREAD

**Issue by link2xt** [webxdc/appstore-bot#9]
[`unwrap_used`](https://rust-lang.github.io/rust-clippy/master/#unwrap_used) ensures that the bot does not panic trying to unwrap some `Option` or `Result`.

Results can be bubbled up with `?` and `Option`s can be converted to errors with [`anyhow::Context`](https://docs.rs/anyhow/latest/anyhow/trait.Context.html) trait.

This is a follow-up for when #8 is merged.

**Comment by Septias** [comment]
What about unwraps where I know that can't happen?
Also, what about things like Bot::new() I don't want to return a result here because an Err should end in a panic.
I don't believe getting rid of unwrap is good in generell.

**Comment by Septias** [comment]
Hm okay, I'll work on it
